name: Build Development Release

on:
  push:
    branches: [ dev ]

jobs:
  build-release:
    name: Build Development Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@v3
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v.${{ github.ref_name }}
          release_name: Development Build (Unpackaged)
          prerelease: true
