# Creates a pre-release for any dev branch commits

name: Build Development Pre-Release

on:
  push:
    branches: [ dev ]

jobs:
  build-release:
    name: Build Development Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Delete existing tag and release
        uses: dev-drprasad/delete-tag-and-release@master
        with:
          delete_release: true # default: false
          tag_name: v.${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Create release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v.${{ github.ref_name }} # Tag name CANNOT equal branch name
          release_name: Development Build (Unpackaged)
          prerelease: true
